// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDffSXDyBCfYjrKb_RYJqWNw1o3-Zxj5Kg',
    appId: '1:1075600342317:android:afd01b044e1fa8a0ada7a4',
    messagingSenderId: '1075600342317',
    projectId: 'lionsbarber-easecorte',
    databaseURL: 'https://lionsbarber-easecorte-default-rtdb.firebaseio.com',
    storageBucket: 'lionsbarber-easecorte.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPHSive34BfIsW7yDzCUtgLjOsM-kszU',
    appId: '1:1075600342317:ios:24c66784d1048c3dada7a4',
    messagingSenderId: '1075600342317',
    projectId: 'lionsbarber-easecorte',
    databaseURL: 'https://lionsbarber-easecorte-default-rtdb.firebaseio.com',
    storageBucket: 'lionsbarber-easecorte.appspot.com',
    iosBundleId: 'com.easecorte.lionsbarberv1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSkH7fXkklP4WMd1aULjxCgoN-k9f8Ok0',
    appId: '1:1075600342317:web:bbb02055ae5f9f0cada7a4',
    messagingSenderId: '1075600342317',
    projectId: 'lionsbarber-easecorte',
    authDomain: 'lionsbarber-easecorte.firebaseapp.com',
    databaseURL: 'https://lionsbarber-easecorte-default-rtdb.firebaseio.com',
    storageBucket: 'lionsbarber-easecorte.appspot.com',
    measurementId: 'G-MH9DBCSBRG',
  );

}